### ISSUE TITLE
Puts broken select2 on billing fields on contribution page

### ISSUE THREAD

**Issue by dsnopek** [civicrm/org.civicrm.shoreditch#133]
When the shoreditch extension (version 0.1-alpha14 and 0.1-alpha12 tested) is enabled, select2 will appear on the credit card and billing address fields, but it's broken.

Here's a screenshot:

![selection_148](https://user-images.githubusercontent.com/191561/34845093-5a1749ae-f6d9-11e7-8543-89d47a1e791f.png)

You can see that both the select2 and vanilla select box are shown. But also, if you click either of them, the options will pop up for a second, and then go away.

This also affects the billing address (which isn't shown in my screenshot), but none of the other select fields (like, on a custom profile on the contribution page, or the "State" field on the non-billing address).

Anyway, this prevents accepting contributions with the Shoreditch extension enabled!

**Comment by mukeshcompucorp** [comment]
@dsnopek  can you provide steps to reproduce this issue?

**Comment by AkA84** [comment]
Fixed by #218 , closing
