### ISSUE TITLE
Font-weight 100 readability

### ISSUE THREAD

**Issue by hansrossel** [civicrm/org.civicrm.shoreditch#139]
In the Chrome font-weight: 100 for Open-Sans is extremely thin and nearly unreadable.

I think for readability it should be at least 400 (regular) or even 700 because Open Sans is already a thin font on its own. Google fonts does not even offer Open-Sans with such an extremely thin font-weight.

<img width="485" alt="schermafbeelding 2018-01-25 om 09 37 55" src="https://user-images.githubusercontent.com/1085054/35378690-f869a388-01b3-11e8-9a3b-4434af0b6a7d.png">
<img width="299" alt="schermafbeelding 2018-01-25 om 09 41 41" src="https://user-images.githubusercontent.com/1085054/35378691-f882c6ec-01b3-11e8-93ff-f7762f2c5266.png">

**Comment by hansrossel** [comment]
It's in /civicrm/_variables.scss
$crm-font-weight-td: 100 !default;

In /bootstrap/fonts/opensans.scss there is only 400, 600 and 700 defined as weight, so should use one of these.

**Comment by AkA84** [comment]
hi @hansrossel , could you provide a screenshot of the issue? I agree that the definition itself of 100 is wrong and should be removed, but In my testing of the issue I could not replicate the problem, as the browser simply picks the lighter font variation available (400)

**Comment by hansrossel** [comment]
There is a screenshot here above in my question above "family selected", it is quite unreadable because very light so you might not have seen it :)
I only started noticing recently that the font was so light in the tables so I suppose the latest update of Chrome is trying to make the font 100 and give us what we ask for.

**Comment by hansrossel** [comment]
I suspect I'm getting 'Open Sans' 300 instead of 100 because I do have 'Open Sans' installed on my computer as a font, so the 300 is available to the system. People that do not have the font installed will then get the Bootstrap minimum 400 which you provide in Shoreditch. 

<img width="287" alt="schermafbeelding 2018-01-25 om 16 02 50" src="https://user-images.githubusercontent.com/1085054/35394865-232251d0-01e9-11e8-9845-b835e2279d3b.png">
Source: https://codepen.io/impressivewebs/pen/EIncg

**Comment by AkA84** [comment]
@hansrossel ok I think the confusion is that, as far as i know, there is no 100 Open Sans. For the rest you are right, if you have the font locally it will show you 300, or if you don't have it locally it will show you 400 (like i see it, since i don't have the font locally)

In any case that value should be definitely removed , thanks for reporting this!

**Comment by AkA84** [comment]
@hansrossel this should be fixed now

**Comment by mukeshcompucorp** [comment]
@AkA84 This is at https://github.com/civicrm/org.civicrm.shoreditch/pull/145, let's close this one
