### ISSUE TITLE
Joomla CIVICRM menu not displaying

### ISSUE THREAD

**Issue by jorich-2000** [civicrm/org.civicrm.shoreditch#147]
Beta15
Civicrm menu is not shown until you click on search

![image](https://user-images.githubusercontent.com/9605017/35775353-1b540d8e-097f-11e8-8c4c-206693ec1285.png)

![image](https://user-images.githubusercontent.com/9605017/35775366-5bd0af3e-097f-11e8-9b13-4c258fcc50aa.png)

**Comment by jorich-2000** [comment]
To fix this I had to change height and line-height to 27px in #civicrm-menu>li.menumain

**Comment by JustinDMoore** [comment]
Same for me. Thanks @jorich-2000 for the workaround. Good now.

**Comment by davidjosephhayes** [comment]
I adding a some custom css to the Isis admin template (css/custom.css) that fixed most of the Joomla specific layout/styling
 problems:

```
body.com_civicrm:not(.toolbar) {
  padding-top: 30px !important;
}
body.com_civicrm .subhead-collapse, body.com_civicrm .subhead-btn  {
  display: none;
}
body.com_civicrm #root-menu-div+.crm-quickSearch-results {
  left: 20px !important;
  top: 165px !important;
}
#crm-container {
  margin-top: 20px;
}
#crm-container ul#civicrm-menu {
  height: 60px;
  padding: 0 !important;
}
#crm-container .label, #crm-container .badge {
  background: transparent;
}
#crm-container .crm-form-block {
  background: transparent;
  border: 1px solid #bbb;
}
```

**Comment by jorich-2000** [comment]
Thanks @davidjosephhayes that works a treat.

**Comment by jorich-2000** [comment]
I also normally add the following to get rid of the left sidebar
#crm-container #sidebar-left {
	display:none;
}

**Comment by mattwire** [comment]
@jorich-2000 Could you test https://github.com/civicrm/civicrm-core/pull/12632 please?

**Comment by jorich-2000** [comment]
@mattwire Overall that seems to work ok - I do still need the following in the joomla admin template custom.css to get the blank joomla sub heading to collapse (it takes a lot of screen space)

body.com_civicrm .subhead-collapse, body.com_civicrm .subhead-btn  {
  display: none;
}

**Comment by mattwire** [comment]
@jorich-2000 Any chance you could post those comments directly on https://github.com/civicrm/civicrm-core/pull/12632?

Also I think this makes sense, but can you raise it as a separate PR against CiviCRM core?
```
body.com_civicrm .subhead-collapse, body.com_civicrm .subhead-btn {
display: none;
}
```

**Comment by AkA84** [comment]
@mattwire civicrm/civicrm-core#12632 has been merged, does it mean i can close this issue?

**Comment by jorich-2000** [comment]
From my point of view yes

**Comment by jorich-2000** [comment]
From my point of view yes
