### ISSUE TITLE
Joomla menus corrupted

### ISSUE THREAD

**Issue by jorich-2000** [civicrm/org.civicrm.shoreditch#148]
beta15
Joomla menu has an additional blank white line added between the menu and title bar
![image](https://user-images.githubusercontent.com/9605017/35775375-8419ee60-097f-11e8-8b9b-f2e74c01728b.png)

**Comment by AkA84** [comment]
Hi @jorich-2000 , thanks for your feedback!

At the moment Shoreditch does not officially support Joomla, but if you'd like to submit a PR to fix the issue we'd gladly review it and consider it for one of the next releases
