### ISSUE TITLE
Use portable resource URL for Custom CSS URL

### ISSUE THREAD

**Issue by themak1985** [civicrm/org.civicrm.shoreditch#160]
This is super low on the priority list - but when you select shoreditch as the custom CSS URL - it generates an absolute URL instead of a portable one - which generates a notice in CiviCRM System Status.  I have avoided this by simply choosing other instead of shoreditch and entering [civicrm.files]/ext/org.civicrm.shoreditch-0.1-alpha15/css/custom-civicrm.css and the warning goes away.

**Comment by davialexandre** [comment]
closing this as shoreditch now uses the new theming system which doesn't rely on the custom CSS URL anymore
