### ISSUE TITLE
404 for fonts

### ISSUE THREAD

**Issue by magnolia61** [civicrm/org.civicrm.shoreditch#2]
I'm getting 404's for
sites/all/modules/civicrm_extensions/org.civicrm.shoreditch/fonts/fontawesome-webfont.woff
sites/all/modules/civicrm_extensions/org.civicrm.shoreditch/fonts/fontawesome-webfont.ttf
sites/all/modules/civicrm_extensions/org.civicrm.shoreditch/fonts/fontawesome-webfont.woff2
sites/all/modules/civicrm_extensions/org.civicrm.shoreditch/fonts/fontawesome-webfont.eot
sites/all/modules/civicrm_extensions/org.civicrm.shoreditch/fonts/fontawesome-webfont.svg

It seems these fonts are located [elsewhere](https://github.com/civicrm/org.civicrm.shoreditch/tree/master/fonts/font-awesome)

**Comment by xurizaemon** [comment]
* What path are your extensions located in?
* What is the civicrm resource URL?

These are in your civicrm admin settings under Directories and URLS pages.

**Comment by xurizaemon** [comment]
Ah, is it the /fontt-awesome/ that's missing or another part of the URL that's wrong?

**Comment by magnolia61** [comment]
My extensions are in: [cms.root]/sites/all/modules/civicrm_extensions/
and my CiviCRM resource url is: [cms.root]/sites/all/modules/civicrm/

The fonts are in fonts/font-awesome/
but the extension seems to be looking only in /fonts

**Comment by totten** [comment]
@magnolia61 , thanks for reporting. Can you double-check that you have the current release `v0.1-alpha2`? The difference between `v0.1-alpha1` and `v0.1-alpha2` is in the handling of font-awesome.

As quick way to check, you might run `md5sum  css/bootstrap.css`
 * `v0.1-alpha1`: ef27fcdd26b70b4e4368584c617f442c
 * `v0.1-alpha2`: 77f9c5a6a31ec80b675fccb5e7ede740

**Comment by colemanw** [comment]
I think this is resolved. I'm no longer seeing the errors on mine.
