### ISSUE TITLE
Booking Wizard Save Button Disappears

### ISSUE THREAD

**Issue by laurynnlowe** [civicrm/org.civicrm.shoreditch#211]
To reproduce:
Booking > New Booking
Select Resource
Add Resource to Basket 
Save Cancel button in Add Resource basket missing

**Comment by jamienovick** [comment]
Hi @laurynnlowe, unfortunately CiviBooking is not yes supported by Shoreditch theme. If you would be able (and willing!) to fund that support we would welcome your contribution. We estimate about 8-12h to fully cover CiviBooking functionality. Please let us know if you would be interested in taking this forward and we can have a more detailed chat. Many thanks!
