### ISSUE TITLE
Contact View - Contact Image not shown

### ISSUE THREAD

**Issue by tschuettler** [civicrm/org.civicrm.shoreditch#215]
A custom contact image can be saved when editing the contact. But it is currently not display on the contact page.

dmaster:
![grafik](https://user-images.githubusercontent.com/19712240/38256302-3b887042-375e-11e8-87a7-26683a696467.png)

current shoreditch:
element is hidden
![grafik](https://user-images.githubusercontent.com/19712240/38256381-6933eb20-375e-11e8-9440-24e49d7e1046.png)

It would probably fit way better in the same way it is done in the CiviHR Demo:
![grafik](https://user-images.githubusercontent.com/19712240/38256501-c01e41a6-375e-11e8-99a7-ec0b5619b252.png)

**Comment by rekaeps** [comment]
Same here, using latest version of Shoreditch and CiviCRM 5.0.0.

Also, is there a reason why there is such a large gap between the name and the summary screen (see my screenshot)? Is it supposed to be like how it's in CiviHR (in the screenshot in OP's post)?

![github](https://user-images.githubusercontent.com/28766405/38445782-fb025d82-39c2-11e8-8c40-dd2e30f62ed9.PNG)

**Comment by Fabian-SYSTOPIA** [comment]
We have a customer who would like to display the image as well and who may be able to fund this. Could anyone provide us with an estimate?

Integrating it left to the display name as tschuettler suggested

**Comment by jamienovick** [comment]
@Fabian-SYSTOPIA I'll pop you an email for estimate. Best

**Comment by AkA84** [comment]
Fixed by https://github.com/civicrm/org.civicrm.shoreditch/pull/264 , closing

**Comment by rekaeps** [comment]
Images are not showing correctly w/ fix. It seems to skew images. I've tried w/ various images. It seems like it needs to be a certain pixel size prior to uploading, otherwise it doesn't know how to crop the image correctly.

![image](https://user-images.githubusercontent.com/28766405/44162088-3da73000-a08d-11e8-84b3-ce0922703621.png)

**Comment by AkA84** [comment]
thanks @rekaeps , yeah i can see that the theme doesn't handle well non-square pictures, we'll have to work on a fix for that. Could you open a new issue for it, so i can close this one? Thanks a lot!
