### ISSUE TITLE
Misalignment when using Drupal Admin Toolbar

### ISSUE THREAD

**Issue by seascoot** [civicrm/org.civicrm.shoreditch#230]
Selecting Admin toolbar to display as a side menu pushes out all of the shoreditch menu dropdowns.

Drupal 8.4.0, Shoreditch 0.1-alpha16, CiviCRM 4.7.30

![image](https://user-images.githubusercontent.com/3943536/39410024-c0deeba8-4ba5-11e8-9c3a-eaa12091b236.png)

**Comment by Rar9** [comment]
Same for Drupal 7

**Comment by AkA84** [comment]
thanks for reporting it @seascoot ! 

Currently Shoreditch does not officially support Drupal 8, but we'd gladly review a PR to fix the issue if you considered submitting one

@Rar9 could you submit more information?

* screenshot (or gif) of the issue
* Shoreditch version
* CiviCRM version
* Steps to reproduce

Thanks!

**Comment by AkA84** [comment]
@Rar9 we currently can't reproduce the issue (shoreditch v0.1-alpha24), so unless you confirm that it's still reproducible on your end and provide all the info i listed above, I think this one can be closed

**Comment by markcarsonmeuk** [comment]
May be related...
Cannot reproduce the above. However, when I view a CiviEvent Info Page while logged in, the admin toolbar has a height of 60px. This obscures the navbar on the main theme (using Bootstrap).
I have tried changing this, with more design issues resulting.
![image](https://user-images.githubusercontent.com/44549789/49096940-99c04980-f263-11e8-8648-bb17af0f6fca.png)
May result to some jquery to avoid this?

**Comment by AkA84** [comment]
@markcarsonmeuk thanks for reporting it, can i ask you to open a separate issue for this with the exact replication steps and info like Shoreditch and CiviCRM version, CMS used, etc? Thanks!
