### ISSUE TITLE
Please don't apply font-family to the body element

### ISSUE THREAD

**Issue by christianwach** [civicrm/org.civicrm.shoreditch#234]
Currently, Shoreditch [applies its sans-serif font stack to the body element](https://github.com/civicrm/org.civicrm.shoreditch/blob/master/scss/civicrm/common/_base.scss#L8). This seems, firstly, to be a divergence from the aim to "contain" Shoreditch's CSS declarations to CiviCRM markup. Secondly, on WordPress, this causes problems both in wp-admin (because it overrides the declarations set by WordPress itself) and on the front-end (because it overrides the theme's default font stack). 

In wp-admin, my CiviCRM Admin Utilities plugin resets the font stack to that which WordPress itself provides, but on the front-end it cannot know what the theme declares since each may be different.

I am aware that the README says that Shoreditch is Drupal-only but there are lots of installs which already use it on WordPress, so removing this declaration seems like a simple fix to prevent unnecessary incompatibility.

**Comment by AkA84** [comment]
> Secondly, on WordPress, this causes problems both in wp-admin (because it overrides the declarations set by WordPress itself) and on the front-end (because it overrides the theme's default font stack).

I'm curious about this, is civicrm initialized both on wp-admin and on public pages? Does it happen by default on WP or is it something that you are doing? Otherwise i'm not exactly clear how the `custom-civicrm.css` would be injected on the page

**Comment by AkA84** [comment]
Closed by #381
