### ISSUE TITLE
Menu's and scrolling - position absolute not fixed.

### ISSUE THREAD

**Issue by stesi561** [civicrm/org.civicrm.shoreditch#235]
I'm not sure if this is due to interference with the CMS theme but I've noticed that drop down menu's are getting position: absolute instead of position: fixed?

I think it is a result of this style being applied inline I assume via javascript?

`<div class="menu-div outerbox" style="position: absolute; top: 0px; left: 657px; margin-top: 6px; display: none;">`

This results in odd behaviour when scrolling the page the menu scrolls with the page.

![menu_absolute](https://user-images.githubusercontent.com/9410526/40698599-e617f14e-6423-11e8-8b80-b3e62b0458bb.gif)

Additionally for very long menu's (the site I was testing it on had a lot of reports) using a mouse scroll wheel while the mouse was within the menu scrolled the page. If the above if resolved it would require allowing some form of scrolling of the menu - otherwise menu items at the bottom of long menus would not be accessible.

Tested with
Shoreditch: 0.1-alpha18, civicm 5.2.beta1
Drupal theme: Seven
With Browsers: Chromium 66, Firefox 60 on linux (ubuntu)

**Comment by AkA84** [comment]
@stesi561 I can replicate the issue on vanilla CiviCRM

![scroll](https://user-images.githubusercontent.com/6400898/45408341-5f83da80-b66c-11e8-88c1-e5d587192ec4.gif)

(v0.1-alpha24)

Are you sure this is a problem with Shoreditch and not with CiviCRM menu in general? That inline style you referenced is applied regardless to whether the theme is enabled or not

**Comment by stesi561** [comment]
Right you are! Random. I've never noticed that before.
