### ISSUE TITLE
FontAwesome not rendering

### ISSUE THREAD

**Issue by christianwach** [civicrm/org.civicrm.shoreditch#27]
[The CSS file](https://github.com/civicrm/org.civicrm.shoreditch/blob/master/css/custom-civicrm.css) generated from the SCSS contains a number of instances of `content:""` which Chrome interprets as `content: "ï†"` causing the checkbox replacements not to render on any CiviCRM admin pages.

![screen shot 2017-07-20 at 15 09 57](https://user-images.githubusercontent.com/726936/28421614-98f04dac-6d5d-11e7-84da-e9d8a20d0d63.png)

**Comment by AkA84** [comment]
@christianwach what page is that screenshot from? Could you tell me what branch you are using of shoreditch and how you enabled the theme? Thanks!

**Comment by christianwach** [comment]
@AkA84 I'm using `master` - the page that the screenshot is from isn't important really (it's the CiviMail Settings page FWIW) it is just an illustration of what I see everywhere that a checkbox should be. It looks to me as though the `content` elements aren't surviving SCSS compilation and are rendering as UTF-8 glyphs in the CSS. Perhaps there's a text encoding problem with the final 'custom-civicrm.css' file?

**Comment by christianwach** [comment]
@AkA84 Compare, for example, the [declarations for radio buttons and checkboxes](https://github.com/civicrm/org.civicrm.shoreditch/blob/master/scss/civicrm/common/_radio-checkbox.scss#L20-L38) and the final output in the CSS file - hard to reference here as it's all on one line, but search for `content:"` in [the CSS file](https://github.com/civicrm/org.civicrm.shoreditch/blob/master/css/custom-civicrm.css) where you'll see glyphs instead of text of the form `\f096`.

**Comment by christianwach** [comment]
> how you enabled the theme

The standard way, via 'Settings - Resource URLs'

**Comment by mukeshcompucorp** [comment]
@AkA84 as a part of https://github.com/civicrm/org.civicrm.shoreditch/pull/123, we do not have styled checkboxes anymore, and hence, this issue is now not produced.

You can close this
