### ISSUE TITLE
Submit Buttons Hidden via custom-civicrm.css

### ISSUE THREAD

**Issue by sleewok** [civicrm/org.civicrm.shoreditch#274]
CiviCRM v5.3 on Drupal 7 using the latest shoreditch pulled from git.

Why are submit buttons on **form popups** being hidden?

This is the CSS in custom-civicrm.css that hides them, which effectively breaks all quickforms loaded through a popup.

`.crm-container.ui-dialog .ui-dialog-content .crm-submit-buttons {
    display: none;
}`

**Details**
This occurs in extensions when using the **loadForm** function to open a form in a popup (dialog) (https://docs.civicrm.org/dev/en/latest/framework/ajax/#crmloadformurl-options) . 

The submit/cancel buttons in the form popup have CSS that matches the CSS (`.crm-container.ui-dialog .ui-dialog-content .crm-submit-buttons) in the shoreditch custom-civicrm.css. This results in the buttons being hidden which means you cannot submit the form. 

This issue was reported for issue https://github.com/civicrm/org.civicrm.shoreditch/issues/211 as well.

**Result WITH custom-civicrm.css:**
![image](https://user-images.githubusercontent.com/304940/43900483-10511280-9bb3-11e8-92d0-1dcc60ea1f51.png)

**Result WITHOUT custom-civicrm.css**
![submitwithoutcustomcss](https://user-images.githubusercontent.com/304940/43900517-28289680-9bb3-11e8-8be7-830d35f452ec.png)

**Comment by AkA84** [comment]
@sleewok  thank you for your feedback, could you please provide:

* screenshots of the issue (preferably how things look in vanilla civicrm, and how they look in shoreditch)
* Info about where you see the issue (i.e. core screens, extension, etc)
* CiviCRM version
* Shoreditch version
* CMS used, and version

**Comment by sleewok** [comment]
Updated with additional information.

**Comment by AkA84** [comment]
thanks @sleewok , if you could also give us the name of the extension used for the screenshot it would help us pinpoint the source of the issue

From core screens I see that when you use `CRM.loadForm`, for example
```js
CRM.loadForm(CRM.url('civicrm/tag/edit', {action: 'add', tagset: 1}))
```
the `.crm-submit-buttons` elements that would normally being shown in the form on full page get instead hidden via JS in the modal, as the modal itself already provides submit buttons

<img width="700" alt="screen" src="https://user-images.githubusercontent.com/6400898/43955968-b245181c-9ca2-11e8-84db-8028ff997b8e.png">

so the theme is really changing nothing there

I'm curious to see why that particular extension (and others, apparently) instead don't get the original submit buttons hidden, and replaced by the modal buttons

**Comment by sleewok** [comment]
The extension that screenshot is from is internal. I noticed something odd. For all of our internally built extensions, when we use the loadForm function I get the following error in the browser console. I wonder if this is the cause of the issue. 

I do not get this error when loading built-in core civi forms. I'm going to do some digging to figure out what is going on...

`ncaught TypeError: Cannot read property 'split' of undefined
    at $.(anonymous function).(anonymous function).isOriginalUrl (http://dev.civicrmdev/sites/all/modules/civicrm/js/crm.ajax.js?pd7a7l:167:34)
    at $.(anonymous function).(anonymous function).isOriginalUrl (http://dev.civicrmdev/sites/all/modules/civicrm/bower_components/jquery-ui/jquery-ui.js?pd7a7l:144:25)
    at HTMLDivElement.<anonymous> (http://dev.civicrmdev/sites/all/modules/civicrm/bower_components/jquery-ui/jquery-ui.js?pd7a7l:256:40)
    at Function.each (http://dev.civicrmdev/sites/all/modules/civicrm/bower_components/jquery/dist/jquery.js?pd7a7l:370:19)
    at jQuery.fn.init.each (http://dev.civicrmdev/sites/all/modules/civicrm/bower_components/jquery/dist/jquery.js?pd7a7l:137:17)
    at jQuery.fn.init.$.fn.(anonymous function) [as crmSnippet] (http://dev.civicrmdev/sites/all/modules/civicrm/bower_components/jquery-ui/jquery-ui.js?pd7a7l:236:10)
    at HTMLDivElement.<anonymous> (http://dev.civicrmdev/sites/all/modules/civicrm/js/crm.ajax.js?pd7a7l:441:34)
    at HTMLDivElement.dispatch (http://dev.civicrmdev/sites/all/modules/civicrm/bower_components/jquery/dist/jquery.js?pd7a7l:5226:27)
    at HTMLDivElement.elemData.handle (http://dev.civicrmdev/sites/all/modules/civicrm/bower_components/jquery/dist/jquery.js?pd7a7l:4878:28)
    at Object.trigger (http://dev.civicrmdev/sites/all/modules/civicrm/bower_components/jquery/dist/jquery.js?pd7a7l:5130:12)
isOriginalUrl @ crm.ajax.js?pd7a7l:167
(anonymous) @ jquery-ui.js?pd7a7l:144
(anonymous) @ jquery-ui.js?pd7a7l:256
each @ jquery.js?pd7a7l:370
each @ jquery.js?pd7a7l:137
$.fn.(anonymous function) @ jquery-ui.js?pd7a7l:236
(anonymous) @ crm.ajax.js?pd7a7l:441
dispatch @ jquery.js?pd7a7l:5226
elemData.handle @ jquery.js?pd7a7l:4878
trigger @ jquery.js?pd7a7l:5130
(anonymous) @ jquery.js?pd7a7l:5860
each @ jquery.js?pd7a7l:370
each @ jquery.js?pd7a7l:137
trigger @ jquery.js?pd7a7l:5859
(anonymous) @ crm.ajax.js?pd7a7l:262
fire @ jquery.js?pd7a7l:3232
fireWith @ jquery.js?pd7a7l:3362
done @ jquery.js?pd7a7l:9840
callback @ jquery.js?pd7a7l:10311
XMLHttpRequest.send (async)
send @ jquery.js?pd7a7l:10254
ajax @ jquery.js?pd7a7l:9738
jQuery.(anonymous function) @ jquery.js?pd7a7l:9890
getJSON @ jquery.js?pd7a7l:9871
refresh @ crm.ajax.js?pd7a7l:242
(anonymous) @ jquery-ui.js?pd7a7l:144
(anonymous) @ jquery-ui.js?pd7a7l:256
each @ jquery.js?pd7a7l:370
each @ jquery.js?pd7a7l:137
$.fn.(anonymous function) @ jquery-ui.js?pd7a7l:236
CRM.loadPage @ crm.ajax.js?pd7a7l:330
CRM.loadForm @ crm.ajax.js?pd7a7l:355
(anonymous) @ sgt_sgDcGroupManage.js?r=RMsXR:66
dispatch @ jquery.js?pd7a7l:5226
elemData.handle @ jquery.js?pd7a7l:4878
`

**Comment by sleewok** [comment]
I just figured it out...
I have to add the parameter "reset: 1" to the URL

That gets rid of the error and the buttons show.

**Comment by sleewok** [comment]
Actually, it doesn't require reset:1. You have to have at least one parameter passed. If you do not have a parameter in the URL then you will get the error. I wonder if that is a bug...

**Comment by AkA84** [comment]
@sleewok thanks for looking a bit more into this! Doesn't seem then that this is a bug with the theme?

**Comment by sleewok** [comment]
@AkA84 Glad to look into it. I am still not sure of the necessity of hiding this element via CSS. 

I am concerned that it may cause issues for many users that have custom extensions using form pop-ups that do not include parameters in the URL. The CiviCRM documentation does not specify this requirement, and the pop-ups seem to function properly without parameters using the default theme. 

In order for us to use this theme I will have to update all of our custom extensions built in-house to include parameters in the pop-ups. 

Hold off on any changes. I am going to submit a bug report to CiviCRM and see where it goes from there.

**Comment by AkA84** [comment]
many thanks @sleewok , i'll wait to hear from you then

>  I will have to update all of our custom extensions built in-house to include parameters in the pop-ups.

Might be interesting checking if all of them gives that error in the console. In that case it might be a sort of requirement that wasn't strictly enforced and/or documented

**Comment by sleewok** [comment]
Looks like it was a bug and is being resolved. I applied the patch that will be included in future releases of CiviCRM and the loadForm popup works with Shoreditch on forms without params in the URL.

https://lab.civicrm.org/dev/core/issues/351
