### ISSUE TITLE
requires "seven" as default theme?

### ISSUE THREAD

**Issue by ahillio** [civicrm/org.civicrm.shoreditch#277]
Is that a typo?  Using this Shoreditch theme for CiviCRM requires that Drupal's default theme be "Seven"?  That's can't be true... using "Seven" as the default theme?  No Drupal site on the planet does that.

I just found Shoreditch via the awesome-looking Contact Layout Editor.  That requires this?  And This requires that the website uses "Seven" as default theme?

**Comment by JoeMurray** [comment]
+1

**Comment by AkA84** [comment]
Hi @ahillio , we don't require the entire Drupal site to use Seven, only the CiviCRM admin.

You can do that by making sure that the "CiviCRM theme" module is enabled, and then selecting the "Seven" theme as "CiviCRM Administration theme" in /admin/appearance

Let me know if you found this helpful, in the meantime we'll make sure to update the README.md to better clarify the relationship with the Seven theme

**Comment by ahillio** [comment]
Aha!  Thanks @AkA84, that makes more sense :)

**Comment by JoeMurray** [comment]
Yes, clarifying this in documentation would be helpful, because I would have thought I needed to set the Civi Admin theme to shoreditch.
