### ISSUE TITLE
Visual Roadmap?

### ISSUE THREAD

**Issue by christianwach** [civicrm/org.civicrm.shoreditch#28]
Is there a visual roadmap for this extension? What I'm interested in are mockups of existing CiviCRM screens that have been fully styled - whether in code or the output of an image editor. I can't seem to visualise the relationship between screen elements from the Bootstrap elements as shown by the [Style Guide](https://github.com/civicrm/org.civicrm.styleguide/).

**Comment by jamienovick** [comment]
@christianwach - Hope you are good. Cleaning up some old tickets here. Can I ask what you mean? Is this specifically for Bootstrap styles? If so we are probably not quite there yet... Could you perhaps give an example of the output that would be helpful to you?

Many thanks

J

**Comment by christianwach** [comment]
@jamienovick Yep, I'm good :) 

TBH, I can't remember exactly what this was about - IIRC, I was trying to fix Shoreditch for WordPress and couldn't get any useful info from the Style Guide. I'll reopen if/when I run into this again.
