### ISSUE TITLE
View Payments -> renders a new page

### ISSUE THREAD

**Issue by KarinG** [civicrm/org.civicrm.shoreditch#30]
Normally we get this [hit the arrow and the Payment details show up underneath]

![image](https://user-images.githubusercontent.com/5340555/28998545-e86df142-79ea-11e7-8c37-806dbf83167f.png)
 
In shoreditch: when I click on the arrow to see the Payment details:
![image](https://user-images.githubusercontent.com/5340555/28998552-06c6603e-79eb-11e7-9e8c-f6d459926f96.png)

I get bumped to a new page:
drupal8.local/civicrm/payment?view=transaction&component=contribution&action=browse&cid=2&id=1&selector=1

![image](https://user-images.githubusercontent.com/5340555/28998554-22fdc8aa-79eb-11e7-98ff-70add6ad9f09.png)

Perhaps I missed something installing Shoreditch (quite possible)...

**Comment by KarinG** [comment]
Ah - my bad - comparing apples and oranges; it's a little mangled on a contact/view -> Contributions tab - but the accordion is working:

![image](https://user-images.githubusercontent.com/5340555/28998570-d9212dca-79eb-11e7-8321-acdbd3e87ad8.png)

Awesome!

**Comment by KarinG** [comment]
Actually - let me leave this issue open - as it I've confirmed it is an issue from the Contributions -> Dashboard screen; i.e. hitting the arrow to view payment details opens up a new page instead an accordion

**Comment by mukeshcompucorp** [comment]
@AkA84 
It seems that issue has something to do with older js or core files,
In current version, we can not re-produce this issue anymore so, we can close this.
