### ISSUE TITLE
Double clicking on save button creates two entities

### ISSUE THREAD

**Issue by marsh-circle** [civicrm/org.civicrm.shoreditch#319]
This used to be a bug in Civi, but I can't reproduce in the sandbox (

When follwing this workflow (link is for sandbox - proving that it works there):

- goto [a contacts summary page](https://dmaster.demo.civicrm.org/civicrm/contact/view?reset=1&cid=43&key=b22712a26a01774adc4db71629ce8b80_4865&context=advanced)
- go to 'Cases' tab
- hit Create Case
- fill out, but on saving hit the save button multiple times

behaviour:
- open the cases tab and there are a few instances of the new case

expected behaviour:
- only one instance

This has been fixed in core, and assuming it's an easy fix to include some JS to diable the button after the first click (but not a dev, sorry :( )

(my ref: 29358)

**Comment by mattwire** [comment]
I think this is still an issue in civicrm core rather than shoreditch.  It is *probably* a timing thing and depends on server speed/how quickly the browser submits as I can only reproduce it on certain sites.  Core PR here: https://github.com/civicrm/civicrm-core/pull/13333
