### ISSUE TITLE
QuickSearch doesn't expand on D8

### ISSUE THREAD

**Issue by MegaphoneJon** [civicrm/org.civicrm.shoreditch#323]
I know that Shoreditch isn't currently targeting Drupal 8.  However, I hadn't seen this reported elsewhere, so it's probably unique to my install or others have a workaround.

Clicking the QuickSearch doesn't allow you to type into it - it just presents the dropdown (see screenshot).

![selection_611](https://user-images.githubusercontent.com/1796012/46551393-a8166880-c8a5-11e8-9eac-6f99002db23e.png)

**Comment by sleewok** [comment]
Make sure you have enabled the extension properly. You can point the CSS to the shoreditch bootstrap, but that does not enable other resources. I have only seen this happen when the javascript is not being loaded that handles that functionality. OR it could be related to your version of jQuery. I would check the console debugger.

**Comment by MegaphoneJon** [comment]
I actually forgot that I posted this ticket or I'd have updated it with what I found.  It's actually a Civi core bug, not a Shoreditch bug.  CiviCRM doesn't currently have a mechanism for adding JS to the footer .  I've [opened an issue](https://lab.civicrm.org/dev/drupal/issues/32) on lab.c.o.

I'm going to close this here - but for others looking for a quick workaround,  you can hack Shoreditch to add the JS to the header instead:
```diff
diff --git a/shoreditch.php b/shoreditch.php
index 41f582d..7db00c0 100644
--- a/shoreditch.php
+++ b/shoreditch.php
@@ -128,8 +128,8 @@ function shoreditch_civicrm_coreResourceList(&$items, $region) {
     CRM_Core_Resources::singleton()->addScriptFile('org.civicrm.shoreditch', 'base/js/tab.js', 1000, 'html-header');
     CRM_Core_Resources::singleton()->addScriptFile('org.civicrm.shoreditch', 'base/js/button.js', 1000, 'html-header');
     CRM_Core_Resources::singleton()->addScriptFile('org.civicrm.shoreditch', 'js/noConflict.js', 1001, 'html-header');
-    CRM_Core_Resources::singleton()->addScriptFile('org.civicrm.shoreditch', 'js/add-missing-date-addons.js');
-    CRM_Core_Resources::singleton()->addScriptFile('org.civicrm.shoreditch', 'js/main-menu.js');
+    CRM_Core_Resources::singleton()->addScriptFile('org.civicrm.shoreditch', 'js/add-missing-date-addons.js', 1002, 'html-header');
+    CRM_Core_Resources::singleton()->addScriptFile('org.civicrm.shoreditch', 'js/main-menu.js', '1003', 'html-header');
```
