### ISSUE TITLE
Make compatible with SlickNav Mobile Menu Extension

### ISSUE THREAD

**Issue by sleewok** [civicrm/org.civicrm.shoreditch#327]
Extension: https://civicrm.org/extensions/slicknav-web-responsive-admin-menu

With Shoreditch installed/enabled the menu is TINY. I'm guessing it is somehow related to the modification to the inline search on the menu. It would be very nice to either include our own mobile menu, or to make it compatible.

If someone can point me in the right direction I could probably resolve it and submit a pull request. I would like to start contributing more, but need some "hand holding" to get moving 👍 .

Lee

**Comment by colemanw** [comment]
I know that @lcdservices has that working for his client.

**Comment by lcdservices** [comment]
Yes, we're using slicknav and the menu sizing looks fine.

**Comment by sleewok** [comment]
There must be a difference in your setup. Any ideas? Here is what ours
looks like:

**Comment by AkA84** [comment]
sorry @sleewok but i need some more details, can you provide the usual: screenshots, civi and shoreditch version, cms version, etc

**Comment by themak1985** [comment]
![slicknav](https://user-images.githubusercontent.com/28904266/48503314-ca3dc780-e80f-11e8-81e4-d1a4c88cee06.PNG)

Similarly here on Wordpress.

**Comment by colemanw** [comment]
FYI this issue will be made obsolete by https://lab.civicrm.org/dev/core/issues/487
