### ISSUE TITLE
Make textarea labels consistent with other field labels re: vertical position

### ISSUE THREAD

**Issue by JoeMurray** [civicrm/org.civicrm.shoreditch#331]
The label for text areas is weirdly placed at the bottom of the field. Sort of overly stylish. This is inconsistent with where labels for other fields are placed and thus poor UX. Please make consistent with other fields and vertical align with top of textarea rather than with bottom. 

![2018-11-02_07-47-21](https://user-images.githubusercontent.com/300943/47913921-331e5a80-de74-11e8-9592-45eacbd368b2.png)

**Comment by JoeMurray** [comment]
It's particularly problematic when there are several textareas in a row intermixed with text fields. Users complain that they end up cursoring into wrong field.

**Comment by AkA84** [comment]
@JoeMurray could you leave informations about shoreditch version, civi version, CMS used, etc, thanks. Also if you could point to a couple of different pages where the issues can be reproduced, it would be helpful as well

**Comment by JoeMurray** [comment]
I've checked on dmaster and don't see the same thing so I will be closing:
![2018-11-04_07-29-18](https://user-images.githubusercontent.com/300943/47964152-73601300-e003-11e8-9e49-360cecd740b4.png)
