### ISSUE TITLE
Performance issues due to Shoreditch CSS

### ISSUE THREAD

**Issue by laryn** [civicrm/org.civicrm.shoreditch#339]
I've been testing Shoreditch on a Backdrop site and really liking the new look. One issue that I've identified: the CSS gets loaded on every page, whether or not it's a CiviCRM page, and whether or not the user has access/permissions for CiviCRM administration at all.

For reference on the difference this makes, I ran a Page Speed Insights report with the Shoreditch CSS selected in the Resource URLs page, and one with the other option selected:
![screen shot 2018-12-03 at 2 42 13 pm](https://user-images.githubusercontent.com/871421/49400357-a6341e80-f709-11e8-8517-2bb60e3900f8.jpg)

The mobile speed score was 2/100. Without the Shoreditch CSS, the mobile speed score jumped to 87/100. Pretty substantial!

Is there a way to load the CSS only if the page actually needs it and the user should actually see it?

**Specs:**
 - Shoreditch v0.1-alpha29
 - CiviCRM 5.7.2
 - Backdrop 1.11.2

**Comment by AkA84** [comment]
hi @laryn this

> the CSS gets loaded on every page, whether or not it's a CiviCRM page, and whether or not the user has access/permissions for CiviCRM administration at all.

seems something more related to how CiviCRM handles the "Custom CSS URL" field than to Shoreditch in particular, do you see the same issue if you put any custom css at all?

Also please check https://lab.civicrm.org/dev/core/issues/378 with i think is relevant to what you are reporting here

**Comment by laryn** [comment]
Ah, thanks!
