### ISSUE TITLE
Icons used by line item edit extension don't show up

### ISSUE THREAD

**Issue by mfb** [civicrm/org.civicrm.shoreditch#353]
When shoreditch custom CSS is in use, the fa-pencil and fa-undo icons used by the line item editor extension are missing - they just show up as boxes.  I am on civi 5.9.1

**Comment by colemanw** [comment]
@mfb can you post a screenshot please?

**Comment by mfb** [comment]
It looks like the problem is scss/civicrm/common/_buttons.scss is forcing the font for `.crm-container .crm-hover-button` to Open Sans, so you get an empty square rather than Font Awesome icon.

![screenshot from 2019-02-26 10-39-05](https://user-images.githubusercontent.com/3278/53437929-82ecd880-39b3-11e9-8807-65accc40a400.png)

**Comment by monishdeb** [comment]
Fixed by https://github.com/civicrm/org.civicrm.shoreditch/pull/360  Closing now.
