### ISSUE TITLE
Error when accessing /civicrm/admin/setting/url?reset=1

### ISSUE THREAD

**Issue by helenagarcia90** [civicrm/org.civicrm.shoreditch#354]
In CiviCRM 4.6.10 it throws an error when accessing **civicrm/admin/setting/url?reset=1**:

`Fatal error: Class 'Civi' not found in /var/www/html/drupal/sites/default/extensions/org.civicrm.shoreditch/shoreditch.php on line 146`

**Comment by MegaphoneJon** [comment]
This extension specifies a minimum version of CiviCRM 4.7, unfortunately.  This error is to be expected.

**Comment by helenagarcia90** [comment]
Mmmh.. ok!

We are planning to updgrade the version, but in the meanwhile I think I've found a solution, so I'm gonna pull request it.

Thanks!
