### ISSUE TITLE
Adjust colours to be compatible with Environment Indicator

### ISSUE THREAD

**Issue by edvanleeuwen** [civicrm/org.civicrm.shoreditch#362]
The combination of the theme and the Environment Indicator results in menu items which are only visible when hovered.

**Comment by colemanw** [comment]
@edvanleeuwen can you post a screenshot please?

**Comment by edvanleeuwen** [comment]
Screenshots of my P and T environment (I am using ski track colours for my OTAP: black-red-blue-green).

![covs-p](https://user-images.githubusercontent.com/7131152/53288516-4dfd3d80-3789-11e9-9805-bd2cd2dc1058.jpg)
![covs-t](https://user-images.githubusercontent.com/7131152/53288517-4dfd3d80-3789-11e9-9543-5a478db662b3.jpg)

**Comment by colemanw** [comment]
Now that a new version of CiviCRM is out the menubar code has been rewritten from the ground up. So this issue is probably not relevant anymore, pending #342
