### ISSUE TITLE
usability - visual differentiation of primary address lost when turning on shoreditch

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/org.civicrm.shoreditch#382]
Without shoreditch I can tell which address entry is primary from the view screen - note the bolding

![Screenshot 2019-03-28 11 40 45](https://user-images.githubusercontent.com/336308/55117055-552fb680-514e-11e9-8d78-b0bbe8cff735.png)

With shoreditch I can't 
![Screenshot 2019-03-28 11 42 03](https://user-images.githubusercontent.com/336308/55117123-8c9e6300-514e-11e9-9d4c-f66b9a8d87bd.png)

**Comment by jamienovick** [comment]
Fixed in latest version @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
thanks @jamienovick
