### ISSUE TITLE
Changes styling of public-facing event info pages

### ISSUE THREAD

**Issue by Upperholme** [civicrm/org.civicrm.shoreditch#387]
I've recently installed Shoreditch on a Drupal 7/Civi site and noticed that the styling of my public-facing event info pages is being modified. I thought Shoreditch was for admin use only?

**Comment by AkA84** [comment]
hi @Upperholme , what version are you using?

**Comment by Upperholme** [comment]
0.1-alpha31

**Comment by AkA84** [comment]
@Upperholme thanks, could you attach some screenshots so we can see what part of the styling is being affected? any steps to reproduce the issue would be useful as well

**Comment by Upperholme** [comment]
First screenshot, with white background, shows an event info page with Shoreditch turned off. Image with non-white background shows the same page with Shoreditch on. Also seeing impacts elsewhere on the site on public-facing pages, notably that enforced padding at the top of the viewport is appearing on my front page at least. This is for a non-logged in user. 

![Screenshot 2019-04-11 at 15 42 14](https://user-images.githubusercontent.com/5860951/55966535-7fb26100-5c70-11e9-9284-92d761b23fc3.png)
![Screenshot 2019-04-11 at 15 40 58](https://user-images.githubusercontent.com/5860951/55966536-7fb26100-5c70-11e9-95f2-c55f5b31d82e.png)

**Comment by Upperholme** [comment]
What I'm unclear about is why Shoreditch is having any impact at all on public-facing pages. Why is the stylesheet being loaded on these pages?

**Comment by jamienovick** [comment]
@AkA84 @Upperholme  I think this may be a combination of issues actually manifesting itself.

1. I believe that CiviCRM does not differentiate between public and private pages in its CSS. In fact all CiviCRM CSS is loaded on public CiviCRM pages in general anyway. They just normally don't have a lot of styling so its less obvious. See here for discussion on this issue: https://lab.civicrm.org/dev/core/issues/300 

2. This is then made worse as Shoreditch more aggressively styles the page and sometimes outside of the main CiviCRM divs. The buttons and and page margin/padding at the top is then affected as well on any page where CiviCRM is bootstrapped.

I think the long term solution to this is to solve 1 above but we have been short of time/budget to do so. I'm not sure if @Upperholme this is something you could help look at perhaps and help us progress?

**Comment by Upperholme** [comment]
Thanks for the info. I'm not sure what I could offer in terms of moving this forward - this is outside my skill set. Whilst I appreciate that the aim is to build a UI that works across different CMSs, Drupal uses the CiviCRM Theme module to enable different themes to be used for front-end (i.e. public-facing) Civi pages. would it not be possible to leverage that approach as an interim solution? (apologies if this is a numpty question)

**Comment by jamienovick** [comment]
@Upperholme  Sorry I updated the gitlab ticket link as it was incorrect.

**Comment by zkrebs** [comment]
Could we somehow switch it to use default Civi css for public facing pages?

**Comment by mattwire** [comment]
@jamienovick @AkA84 @Upperholme I suggest you take a look at this PR https://github.com/civicrm/org.civicrm.shoreditch/pull/316 which explains the issues pretty well and offers a good solution.

**Comment by AkA84** [comment]
hi @Upperholme I only know managed to get back to this, apologies.

As I wrote in a [comment](https://lab.civicrm.org/dev/core/issues/378#note_20923) that I left on the issue that Jamie previously linked, we made and are still making improvements to prevent leakage of shoreditch's styles on public pages, but this still look like to be mainly an issue with Civi rather than with our theme

Just to confirm that, I believe that you would have issues with any stylesheet you would put in the "Custom CSS URL" field on `/civicrm/admin/setting/url`, correct? As long as the stylesheet contained any generic enough ruleset, like
```css
/* some-custom-stylesheet.css */

/* This should make any public page get a red border around them */
.page-civicrm {
  border: 2px solid red;
}
```

**Comment by jamienovick** [comment]
Fixed in latest version of shoreditch as this only styles within the CiviCRM container. Note that Drupal users should also install the companion Drupal theme found here: https://github.com/compucorp/shoreditch-companion-d7-theme
