### ISSUE TITLE
The 5.12.1 menu lacks color styling when used with Shoreditch

### ISSUE THREAD

**Issue by johncronan** [civicrm/org.civicrm.shoreditch#388]
This showed up for me after installing 5.12.1. In 5.12.0 there were also menu changes, but this problem with the colors was not present.

I'm not sure whether it's meant to be light or dark anymore!

![Screen Shot 2019-04-16 at 9 47 34 PM](https://user-images.githubusercontent.com/159399/56257312-6dca2700-6091-11e9-9fba-571cc242feca.png)

My Shoreditch version is 0.1-alpha31 and my Drupal version is 8.6.14.

edited to add: I probably should have quit out of Flux before taking the screenshot - that's why it's yellowish.

**Comment by MegaphoneJon** [comment]
I had the same problem with D8, but doing either `cv flush` or `drush cr` fixed it for me.  However - I think you have a secondary problem in this screenshot that I did - the text in the Quicksearch box is an off-white.  Can you confirm if that's happening for you?

**Comment by johncronan** [comment]
It's still happening for me after `cv flush` and `drush cr`.

When you type text into the quicksearch it's hard to read, yes:

![Screen Shot 2019-04-17 at 1 29 47 PM](https://user-images.githubusercontent.com/159399/56312071-03f36100-6115-11e9-9eb4-2d8595b8d3a9.png)

**Comment by MegaphoneJon** [comment]
Sorry to hear that it didn't fix things for you!  Meanwhile, I was able to replicate the off-white issue on a non-Shoreditch site - it's CMS theme-dependent, but separate from Shoreditch so I'll take this elsewhere.

**Comment by johncronan** [comment]
Oh, okay. Well, this is not a functional issue with the site. I can afford to see if it shakes out in a coming point release, or something like that.

**Comment by MegaphoneJon** [comment]
@johncronan FWIW, I just submitted a patch on the Quicksearch color issue, and it's already been merged: https://github.com/civicrm/civicrm-core/pull/14080

**Comment by colemanw** [comment]
5.12.1 introduced configurable menu colors. With Shoreditch enables you should change the color to white.

**Comment by johncronan** [comment]
Change it where? I can't find the setting.

**Comment by colemanw** [comment]
Admin -> Customize Data & Screens -> Display Prefs

**Comment by johncronan** [comment]
That worked. Thanks!
