### ISSUE TITLE
Use class instead of id for `bootstrap-theme`

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/org.civicrm.shoreditch#39]
I find it a bit odd that I need to set `id="bootstrap-theme"` to use Shoreditch. I would expect this to be `class="bootstrap-theme"`. Was the choice to use `id` intentional? If so why?

**Comment by colemanw** [comment]
:+1: for this request. Using an id means only one region of the page can be themed with bootstrap.

**Comment by AkA84** [comment]
I would have liked to use the class as well, but unfortunately the theme needs an id for the namespace, so that you can be sure that it takes precedence over any other styles (the id having a bigger weight than a class)

**Comment by mukeshcompucorp** [comment]
@AkA84 This one is answered and makes sense already, we can close this
