### ISSUE TITLE
Contact summary name field labels invisible due to white font color

### ISSUE THREAD

**Issue by jensschuppe** [civicrm/org.civicrm.shoreditch#390]
When on the contact summary, while editing the contact name fields, their labels are not visible due to them being rendered with white font color. This is caused by the selector `.page-civicrm-contact-view:not([class*='page-civicrm-contact-view-'])` which does not match the body class of the contact summary page: `page-civicrm-contact-view` (nothing appended with a dash).

Screenshot: 
![shoreditch-contact_summary-labels-white_font](https://user-images.githubusercontent.com/29565644/57219636-fc7af580-6ff8-11e9-9b91-47b594d4ef1e.png)

Bug confirmed on CiviCRM 5.10.4 and 5.12.1.

**Comment by jensschuppe** [comment]
It's CiviCRM's `contactSummary.css` setting the background color to white and Shoreditch setting the label color tho white (compiled selector: `.page-civicrm-contact-view:not([class*='page-civicrm-contact-view-']) #crm-container form.CRM_Contact_Form_Inline_ContactName .crm-inline-edit-form>.crm-inline-edit-field label`). So, Shoreditch should either set the background to a darker color or leave the label color alone.

This is still valid with Shoreditch 0.1-alpha32.

**Comment by jamienovick** [comment]
Fixed in latest version of Shoreditch so closing
