### ISSUE TITLE
Quicksearch looks weird on 5.13

### ISSUE THREAD

**Issue by lolaslade** [civicrm/org.civicrm.shoreditch#391]
Our first test on 5.13 showed some breakage around quicksearch and whitespace on the right side of the menu. This was with Drupal 7.67 and Seven admin theme.

![shoreditch](https://user-images.githubusercontent.com/2320484/57645774-01a5ea80-758d-11e9-904d-5cc863bdd992.png)

**Comment by jusfreeman** [comment]
The workaround is to make the CiviCRM menu white, in the display preferences -> civicrm/admin/setting/preferences/display?reset=1

Thanks @seamuslee001

**Comment by colemanw** [comment]
This bug has been filed quite a few times so I'm going to close it as a duplicate.
Please see #386
