### ISSUE TITLE
Menu Visible on Print (Action > Print Selected Rows)

### ISSUE THREAD

**Issue by sleewok** [civicrm/org.civicrm.shoreditch#412]
Printing selected rows from a search result includes the main menu on the print. It should be hidden from printing. 

![image](https://user-images.githubusercontent.com/304940/63694488-905d1100-c7e4-11e9-9a39-041e1f9f5f1d.png)

Print Preview:
![image](https://user-images.githubusercontent.com/304940/63694531-a4a10e00-c7e4-11e9-9419-f2c63403ecc2.png)

**Comment by jamienovick** [comment]
@sleewok have you tested this on vanilla CiviCRM and can you confirm it is not a core issue? Thanks

**Comment by sleewok** [comment]
Looks like it is a bug in core. I'll submit it!
