### ISSUE TITLE
Where and how to enable CiviCRM Theme?

### ISSUE THREAD

**Issue by joemcl** [civicrm/org.civicrm.shoreditch#418]
A requirement is that 
```"CiviCRM Theme" module [is] enabled```
but I don't see that as a Component, it's not an Extension listed in the directory, and there is a really old Drupal module listed at https://www.drupal.org/project/civicrm_theme with a note about 
```For drupal 7.x this module has been move to CivCRM core and it will be available in CiviCRM v4.0.5 onwards.```
So does this refer to the really old Drupal module?
Thanks!

**Comment by seamuslee001** [comment]
@joemcl it wouldn't i believe it refers to a type of CiviCRM extension see https://docs.civicrm.org/dev/en/latest/framework/theme/

**Comment by joemcl** [comment]
@seamuslee001 cool, thanks!

**Comment by joemcl** [comment]
aha, looks like this refers to a Drupal module - 
![CiviCRMTheme](https://user-images.githubusercontent.com/3912434/64596793-6de10100-d369-11e9-816a-adcb13ce5253.jpeg)

**Comment by davialexandre** [comment]
@joemcl yes, that is the module that should be enabled!
