### ISSUE TITLE
Body class for custom-civicrm.css?

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/org.civicrm.shoreditch#42]
I'm writing an extension using `crm-*` markup and I'd like it to look good with or without `custom-civicrm.css` from Shoreditch. But it's a little hard for me style it *one way* which looks great in both cases. Is there a way I can detect when the Shoreditch `custom-civicrm.css` is turned on, ideally with CSS? I think it'd be neat to have something like `.shoreditch` on `<body>` for this purpose. Is there already something I can grab onto somewhere?

**Comment by christianwach** [comment]
I test for Shoreditch in my CiviCRM Admin Utilities plugin and load different CSS files depending on whether the Shoreditch CSS file is active or not. [Have a look ay my code here](https://github.com/christianwach/civicrm-admin-utilities/blob/master/civicrm-admin-utilities.php#L225-L244). Hope this helps :)

**Comment by AkA84** [comment]
@seanmadsen can you give me more details on why it's difficult to make it look good with *and* without `custom-civicrm.css`?

**Comment by seanmadsen** [comment]
I worked around this issue another way. Would love to explain more, but I just don't have time right now to dig back into that project. Sorry! 

Thanks to @mukeshcompucorp for reaching out via Mattermost about closing this ticket.
