### ISSUE TITLE
Transparent navigation menu is difficult to read

### ISSUE THREAD

**Issue by larssg-wildsight** [civicrm/org.civicrm.shoreditch#427]
The theme is great and a big improvement, but there is one detail in particular that is a downgrade, from my perspective. The transparent menus can make it hard to read the menu items when there is text underneath them. This is a particular problem in the Admin menu or when looking at the Reports menu, as these menus are usually busier. The small degree of transparency in the menus can makes it sometimes harder than it needs to be to quickly find the menu item you are looking for.

Is this something others are finding as well?

**Comment by sleewok** [comment]
What transparent menus? I do not have any menus that are transparent.

**Comment by larssg-wildsight** [comment]
Apologies, this appears to have been on an older version. Had some issues with setting of theme css and was not on the version that I thought I was on.
