### ISSUE TITLE
Manage Groups doesn't render properly

### ISSUE THREAD

**Issue by samp3** [civicrm/org.civicrm.shoreditch#455]
The box width is wrong. You cant see edit button for example. It seems that the box width is tied to the green help message:

Use Groups to organize contacts (e.g. these contacts are part of our 'Steering Committee'). You can also create 'smart' groups based on contact characteristics (e.g. this group consists of all people in our database who live in a specific locality). 

Using Google Chrome on desktop.

**Comment by jamienovick** [comment]
Hi @samp3 could you share a screenshot to give us a few more details of the issue? 

Could you also confirm the exact version of Shoreditch and CiviCRM you are using?

Many thanks

**Comment by samp3** [comment]
![bootstrap_broken](https://user-images.githubusercontent.com/14363137/84399458-8f795c80-ac09-11ea-939e-867e51f92b8d.png)

civicrm: 5.26.1
shoreditch: 1.0.0-beta.1

**Comment by jamienovick** [comment]
@samp3 Could you clarify:
- Which CMS you are using
- Which CiviCRM admin theme you are using

Also, when you say the "box width is wrong" - which box? 

The screenshot above appears to be cutoff for some of the page?

**Comment by samp3** [comment]
* CMS: drupal 7.69
* Default admin theme

The screenshot shows the full width of the box the page shows. You cant see the right part of the infromation. It is cut off after "Visibilit...". So for example editin a group is really tedious.

I would assume your window width on bootstrap is locked to the width of the green message since it is exactly as wide as the box. It is just my assumption.

**Comment by jamienovick** [comment]
Thanks @samp3 

Unfortunately CiviCRM (and Shoreditch) are not responsive currently.

Can I ask what display resolution your screenshot is at? I would expect that you would need at least 1280px width for the screen to work appropriately.

Best

Jamie

**Comment by samp3** [comment]
1920x1080. Here is full screenshots. That first screentshot is snipped.

![bootstrap_top](https://user-images.githubusercontent.com/14363137/84901500-3d768200-b0b4-11ea-96e4-0e2879e56c44.png)
![bootstrap_bottom](https://user-images.githubusercontent.com/14363137/84901532-46ffea00-b0b4-11ea-9c6e-018411019cf1.png)

**Comment by jamienovick** [comment]
Thanks @samp3 have you tried setting up:

https://github.com/compucorp/shoreditch-companion-d7-theme

You should set this to be your CiviCRM administration theme in the Drupal theme settings: https://nimb.ws/p2BU1H

Best

**Comment by samp3** [comment]
My shoreditch companion shows in appereance but it is not located under CiviCRM adminstration theme in Drupal settings. Did I fail the installation. Enabling the theme didnt change anything AFAIK.

![aa](https://user-images.githubusercontent.com/14363137/85862953-211cc880-b7cb-11ea-81a0-1bbbffd1cb12.JPG)

**Comment by jamienovick** [comment]
@samp3 Your screenshot above doesn't appear to show the CiviCRM administration theme, but only shows the Drupal admin them options. 

Have you enabled that module in the Drupal module list?

**Comment by samp3** [comment]
Lol I had CiviCRM Theme disabled. Now everything is working as I want to :) Thank you kind sir!
