### ISSUE TITLE
No access to addtional option on Custom data fields

### ISSUE THREAD

**Issue by chumkui** [civicrm/org.civicrm.shoreditch#464]
CiviCRM 5.27.4
Drupal 7.72
Shoreditch 1.0.0-beta.1
Google Chrome

I was trying to delete a custom field today and relalised that there was no option for deletion - all you can do is edit and preview.  I scratched my head a bit and realised that there was no access to the 'more' options on the menu.  All I did was temporarily disable the Shoreditch theme to get the delete option back. I have attached two pngs to describe the issue.
<img width="552" alt="with Shoreditch" src="https://user-images.githubusercontent.com/18424420/89659446-d1501780-d8c7-11ea-8df3-930d4820eb07.png">
<img width="416" alt="without Shoreditch" src="https://user-images.githubusercontent.com/18424420/89659447-d2814480-d8c7-11ea-88f9-7f6bb10b4349.png">

**Comment by MegaphoneJon** [comment]
Duplicates #457.

**Comment by marcelocompucorp** [comment]
#469

**Comment by marcelocompucorp** [comment]
Hi all,

A new Shoreditch version with a fix for this issue has just been released: https://github.com/civicrm/org.civicrm.shoreditch/releases/tag/1.0.0-beta.2

Cheers,

**Comment by reneolivo** [comment]
Closed since this issue has been fixed by https://github.com/civicrm/org.civicrm.shoreditch/pull/469 which has also been released.

Thanks for your help @chumkui
