### ISSUE TITLE
More link for price sets, profiles, recurring contributions, etc not displaying

### ISSUE THREAD

**Issue by larssg-wildsight** [civicrm/org.civicrm.shoreditch#465]
The More link for price sets, price fields, profiles, recurring contributions, etc (where the links to disable, delete, copy, settings, etc are found) is not displaying. The link is still there, but it is just a small blank area. It should be three small dots vertically, but it is just a blank area now. Disabling Shoreditch resolves the issue.

Shoreditch 1.0.0 (same issue in 0.33) and CiviCRM 5.28. Issue is not present on CiviCRM 5.26.2.

![Screen Shot 2020-08-07 at 11 22 34 AM](https://user-images.githubusercontent.com/25517556/89671633-91296e80-d8a0-11ea-9d53-f4dc270a0df0.png)

**Comment by MegaphoneJon** [comment]
Duplicates #457.  @jamienovick This is the fourth ticket on a pretty serious issue - any chance of a fix?  #457 discusses a number of potential fixes.

**Comment by Detsieber** [comment]
Also not displaying in list of mailings.

**Comment by jamienovick** [comment]
@MegaphoneJon We are working on this currently as the security release is out and should have an update in the next few days. Best
