### ISSUE TITLE
nodejs version 5 no longer maintained

### ISSUE THREAD

**Issue by mattwire** [civicrm/org.civicrm.shoreditch#47]
Unfortunately nodejs v5 is no longer maintained.  The recommendation is to move to either nodejs v4 (LTS) or nodejs v6.  We are having issues with buildkit/buildkit derived tools needing updated versions of nodejs and being forced to use v5 because of shoreditch.

I see in the build notes:
"First of all you need NodeJS. Please be aware that currently Shoreditch does not support NodeJS v6 or higher! It is recommended that you install NodeJS v5.12.0 (you can use nvm for managing multiple node versions on the same machine."

So _why_ does shoreditch no support v6 or higher?  And _what_ would be required to move it to nodejs v6?

**Comment by AkA84** [comment]
@mattwire unfortunately the SASS for the custom-civicrm.css stylesheet (that styles the core screens) had been written making an extensive use of the SASS `@extend` directive, which is [known](https://www.sitepoint.com/avoid-sass-extend/) to be quite problematic.

When most of the initial stylesheet was written, it was done so using the node-sass v3.4.2 npm package, which processed `@extend` in a certain way. Upgrading to a node version higher than 5.x.x causes the node-sass version to be bumped to, which in turns process the `@extend` directive in a different way, causing a lot of styling issue.

As a temporary workaround (giving that disentangling the SASS code from all the `@extend`s could be quite complicated), we decided to just suggest to use node 5 for the time being

Hope this clarifies the issue somewhat

**Comment by mukeshcompucorp** [comment]
@AkA84 Node is with Latest 8.9.4 from https://github.com/compucorp/org.civicrm.shoreditch/pull/81 we can close this
