### ISSUE TITLE
Cancel Butten formate error

### ISSUE THREAD

**Issue by Rar9** [civicrm/org.civicrm.shoreditch#478]
for Drupal 7 Civicrm 5.31 + last version of shoreditch the **CANCEL Button** on inline edit is missing a border or background color
![Screenshot_1](https://user-images.githubusercontent.com/2239608/98654403-8f0efa00-233e-11eb-8976-eca2fd2715b9.jpg)

**Comment by chumkui** [comment]
There are a few glitches like this one.  I have just upgraded to 5.35.1 and also updated Shoreditch to beta.5.  beta.4+ fixes a couple of issues, but not this one.  This particular issue is still present along with a couple of more troublesome ones like the cases dashboard.

**Comment by j-p-o** [comment]
I'm on 5.35.1 and ShoreDitch 0.1.0-alpha.36. I also saw a few button problems. I tried fixing them. The result is in the patch in attachment. For what its worth.

[repairing_shoreditch_buttons.patch.zip](https://github.com/civicrm/org.civicrm.shoreditch/files/6245017/repairing_shoreditch_buttons.patch.zip)
