### ISSUE TITLE
Dashboard Design since 5.32

### ISSUE THREAD

**Issue by themak1985** [civicrm/org.civicrm.shoreditch#484]
Hey folks, are there any planned changes to dashboard display in shoreditch since introduction of 5.32 - we recently upgraded to 5.33.1 and noticed the change. Not sure if unique to us or an issue.

![Screen Shot 2021-01-13 at 6 47 25 PM](https://user-images.githubusercontent.com/28904266/104526453-6b7f5e80-55d0-11eb-85fa-f5dee26275c0.png)

**Comment by eileenmcnaughton** [comment]
I've had a customer report this as an issue - it's possible the present on an [empty dashlet](https://lab.civicrm.org/dev/core/-/issues/2420) confused here but I created a civicrm 5.30 build to compare

5.30 (with git master shoreditch)


![image](https://user-images.githubusercontent.com/336308/109082996-e60fd200-7769-11eb-8879-7d6fd3c19383.png)

CiviCRM master branch  (with git master shoreditch)

![image](https://user-images.githubusercontent.com/336308/109083055-08a1eb00-776a-11eb-9b5d-85bd28dcd921.png)

**Comment by jamienovick** [comment]
@eileenmcnaughton have replied on mattermost, would be great to chat there. best

**Comment by eileenmcnaughton** [comment]
Just noting the short version is - Compucorp would love someone to fund them around this

**Comment by deb1990** [comment]
This has been fixed in the latest release https://github.com/civicrm/org.civicrm.shoreditch/releases/tag/1.0.0-beta.5

**Comment by eileenmcnaughton** [comment]
Thanks @deb1990
