### ISSUE TITLE
PHP Deprecated: Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by Rar9** [civicrm/org.civicrm.shoreditch#486]
Since upgrade to civicrm 5.34 for drupal 7 + 9 with php 7.4 I'm getting

PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/vhosts/xxx/sites/default/files/civicrm/ext/org.civicrm.shoreditch/shoreditch.civix.php on line 246

**Comment by Rar9** [comment]
Any update on this PHP upgrade?

**Comment by wintermoor** [comment]
This file is Civix generated. You may hot-fix it in line 246 by changing {0} to [0]. 

See: https://github.com/totten/civix/issues
