### ISSUE TITLE
Shoreditch not working after upgrade to 5.35.beta1 - WordPress

### ISSUE THREAD

**Issue by wintermoor** [civicrm/org.civicrm.shoreditch#489]
Upgraded to 5.35.beta1 recently and am unable to enjoy my Shoreditch theme (v 1.0.0-beta.4) with my WordPress 5.6.1 anymore. I'm very unsure why, but it is falling back to old-fashioned Drupal standard. 

I have good experience with the extension https://lab.civicrm.org/extensions/shoreditchwpworkarounds fixing some CSS-issues, but this is not related with shoreditchwpworkarounds. 

Did anyone noticed this behaviour, too?

**Comment by Upperholme** [comment]
It may be out of date, but the information published at https://civicrm.org/extensions/shoreditch lists Drupal 7 as a requirement, i.e. Shoreditch isn't built for Wordpress?

**Comment by wintermoor** [comment]
You are right! But it's running smooth on Civi 5.33 & 5.34 with WordPress. Changing to 5.35.beta1 is breaking it. This information may be helpful to the folks here.

**Comment by deb1990** [comment]
@wintermoor +1 . Currently Wordpress is not supported.

**Comment by wintermoor** [comment]
Is working with 5.53.0 now. I'm using https://lab.civicrm.org/extensions/shoreditchwpworkarounds for better integration to WP.
