### ISSUE TITLE
Latest versions not available on CiviCRM extension page

### ISSUE THREAD

**Issue by larssandergreen** [civicrm/org.civicrm.shoreditch#493]
I had an issue here that it turns out was resolved by upgrading to 1.0.0-beta4. I thought I was on the most recent version as nothing had been added to the CiviCRM extensions page. Possible to add the latest beta to that page so people can find it?

**Comment by eileenmcnaughton** [comment]
@mlutfy any idea?

**Comment by eileenmcnaughton** [comment]
Ah @mikeymjo says it needs manual creation due to the build steps

**Comment by eileenmcnaughton** [comment]
Listed releases https://civicrm.org/extensions/shoreditch

**Comment by eileenmcnaughton** [comment]
@reneolivo this will affect the release you are just working on too -  see https://civicrm.org/extensions/shoreditch

**Comment by deb1990** [comment]
@eileenmcnaughton thanks for the info. 
Could you elaborate on which build steps are causing this? 
The Extension page lists 1.0.0-beta.1. But in 1.0.0-beta.2 no new build steps were added https://github.com/civicrm/org.civicrm.shoreditch/compare/1.0.0-beta.1...1.0.0-beta.2.

**Comment by MikeyMJCO** [comment]
@deb1990 please see https://chat.civicrm.org/civicrm/pl/77bd9zfgwtbejfkqpq6mtd1g7y

**Comment by deb1990** [comment]
This has been fixed now, and from now on all releases will be automatically published. All thanks to @mlutfy.

**Comment by larssandergreen** [comment]
Thanks @mlutfy!
