### ISSUE TITLE
drupal 9 support?

### ISSUE THREAD

**Issue by Rar9** [civicrm/org.civicrm.shoreditch#522]
I cloned your last git and applied to t civicrm 5.38.0 with seven base theme.
 
 but it look different to what I see with drupal 7 with bootstrap base theme.

Is this theme actually still compatible?

**Comment by Rar9** [comment]
![image](https://user-images.githubusercontent.com/2239608/121887954-b6380a80-cd17-11eb-9cb3-b7e11d610bb3.png)


Yes i have already also installed the  class custom module

**Comment by deb1990** [comment]
@Rar9 As mentioned in the [Readme](https://github.com/civicrm/org.civicrm.shoreditch#requirements), at the moment Shoreditch only supports Drupal 7.
