### ISSUE TITLE
Front end url's treat differently for shoreditch

### ISSUE THREAD

**Issue by yashodha** [civicrm/org.civicrm.shoreditch#563]
We have different result on these 2 urls'

https://www.example.org/civicrm/event/info%3Fid%3D443%26reset%3D1 
shoreditch is loaded

https://www.example.org/civicrm/event/info?id=443&reset=1
shoreditch is not loaded, looks different

**Comment by yashodha** [comment]
@olayiwola-compucorp have you encountered the same?

**Comment by yashodha** [comment]
@olayiwola-compucorp you could check here :
https://dmaster.demo.civicrm.org/civicrm/event/info?reset=1&id=3

https://dmaster.demo.civicrm.org/civicrm/event/info%3Fid%3D3%26reset%3D1

**Comment by olayiwola-compucorp** [comment]
@yashodha, The URLs are the same, save that one is encoded, I haven't encountered it myself.

Do you think this is an issue?
