### ISSUE TITLE
CIVUP-39 Contact overview information on the Summary tab displaying in wrong position.

### ISSUE THREAD

**Issue by agileware-ploy** [civicrm/org.civicrm.shoreditch#59]
Agileware are happy to work on this issue. Please let us know if anyone on your team is currently working on it so we do not duplicate our efforts.

**Summary tab**
Contact summary is displayed in wrong position, it appears in the bottom of the page, which is not consistent with other tabs. The details of other tabs are displayed on the right hand side.

![contact_summary](https://user-images.githubusercontent.com/32181595/30731668-1ca81d1a-9fb2-11e7-833e-c894e5e0da16.png)

**Comment by jusfreeman** [comment]
See PR #52 - Fix contact summary display

**Comment by agileware-fj** [comment]
This appears to be fixed according to our testing.  Please close.
