### ISSUE TITLE
CIVUP-40 Table on the Activities tab not displaying properly, blank space appears on the right side

### ISSUE THREAD

**Issue by agileware-ploy** [civicrm/org.civicrm.shoreditch#60]
Agileware are happy to work on this issue. Please let us know if anyone on your team is currently working on it so we do not duplicate our efforts.

When go to the contact record and navigate to activity tab, the screen below appears. The table not displaying properly, blank space appears on the right hand side.

![activities_tab](https://user-images.githubusercontent.com/32181595/30731756-a4a8bd00-9fb2-11e7-9226-f9ddf335f87e.png)

![activity tab space](https://user-images.githubusercontent.com/32181595/30731757-a4db0742-9fb2-11e7-952d-fa48cd98d4fe.png)

**Comment by agileware-fj** [comment]
Confirming this is fixed.

**Comment by mukeshcompucorp** [comment]
@AkA84 This one is fixed at https://github.com/civicrm/org.civicrm.shoreditch/pull/204,
We can close this
