### ISSUE TITLE
CIVUP-41 The pop up block on the Activity tab not displaying correctly

### ISSUE THREAD

**Issue by agileware-ploy** [civicrm/org.civicrm.shoreditch#61]
Agileware are happy to work on this issue. Please let us know if anyone on your team is currently working on it so we do not duplicate our efforts.

1. When clicking on more options menu (⋮), the pop up menu block appears behind the next line. Please see screenshot.

![activity_-_menu_overlap](https://user-images.githubusercontent.com/32181595/30731833-1431a1c8-9fb3-11e7-8197-3f9d257516df.png)

2. When hover on the individual icon, the pop up of contact detail not displaying properly.

![activity-tab](https://user-images.githubusercontent.com/32181595/30731834-1431d9fe-9fb3-11e7-8ce6-74a766693ebc.png)

**Comment by agileware-fj** [comment]
Currently working on a fix for this.

**Comment by mukeshcompucorp** [comment]
@AkA84 This is fixed as a part of https://github.com/civicrm/org.civicrm.shoreditch/pull/206 we can close this
