### ISSUE TITLE
CIVUP-42 View details link is not clickable on the Contributions dashboard

### ISSUE THREAD

**Issue by agileware-ploy** [civicrm/org.civicrm.shoreditch#62]
Agileware are happy to work on this issue. Please let us know if anyone on your team is currently working on it so we do not duplicate our efforts.

When go to the Contributions dashboard and choose Table layout, view details link is not clickable.

![civicontribute](https://user-images.githubusercontent.com/32181595/30731918-78e7a298-9fb3-11e7-997f-681a052d8b38.png)

**Comment by agileware-fj** [comment]
We have a fix ready for this.  PR incoming soon.

**Comment by mukeshcompucorp** [comment]
@AkA84  This is fixed as part of https://github.com/civicrm/org.civicrm.shoreditch/pull/206 we can close this
