### ISSUE TITLE
CIVUP-43 Pop up contact information box not displaying correctly on Find Contributions page

### ISSUE THREAD

**Issue by agileware-ploy** [civicrm/org.civicrm.shoreditch#63]
Agileware are happy to work on this issue. Please let us know if anyone on your team is currently working on it so we do not duplicate our efforts.

When hover on the individual icon on Find Contribution page, the pop up box not displaying properly. The background is not full fill the whole box. It is also hard to see the text because the text colour and background colour do not contrast enough.

![contact summary popup](https://user-images.githubusercontent.com/32181595/30731978-c1ad7e6c-9fb3-11e7-9c30-d3673e1c8711.png)

**Comment by agileware-fj** [comment]
This appears fixed.  Please close.

**Comment by mukeshcompucorp** [comment]
@AkA84  This is fixed as part of https://github.com/civicrm/org.civicrm.shoreditch/pull/206 we can close this
