### ISSUE TITLE
CIVUP-44 When clicking on the more ( ⋮ ) button on Event dashboards, the menu box overlaps and appears behind text.

### ISSUE THREAD

**Issue by agileware-ploy** [civicrm/org.civicrm.shoreditch#64]
Agileware are happy to work on this issue. Please let us know if anyone on your team is currently working on it so we do not duplicate our efforts.

When go to the Event dashboards and clicking on the more button in Event summary section, the menu box overlaps and appears behind text.

![civievent](https://user-images.githubusercontent.com/32181595/30732028-eebb7d0a-9fb3-11e7-86e4-1ed01ed3024a.png)

**Comment by agileware-fj** [comment]
This appears to be fixed.  Please close.

**Comment by mukeshcompucorp** [comment]
@AkA84 This is fixed with table global changes, we can close this
