### ISSUE TITLE
CIVUP-45 The radio button not displaying correctly in Edit Search Criteria section on Find participants page

### ISSUE THREAD

**Issue by agileware-ploy** [civicrm/org.civicrm.shoreditch#65]
Agileware are happy to work on this issue. Please let us know if anyone on your team is currently working on it so we do not duplicate our efforts.

On Find participants page, criteria text and the 2nd radio button not displaying properly. Cannot see the text at all from the 2nd radio button.

![find_participants_-_radiobutton](https://user-images.githubusercontent.com/32181595/30732086-2c60483e-9fb4-11e7-897e-618ac2f8f3bb.png)

**Comment by agileware-fj** [comment]
"Select Records" radio is working.

Criteria is still narrow.  This is on our to-fix list.

**Comment by mukeshcompucorp** [comment]
@AkA84 as a part of https://github.com/civicrm/org.civicrm.shoreditch/pull/123, we do not have styled radio buttons anymore, and hence, this issue is now not produced.

You can close this
