### ISSUE TITLE
CIVUP-46 The individual, organisation and household icon on Find participants page does not pop up a contact summary box

### ISSUE THREAD

**Issue by agileware-ploy** [civicrm/org.civicrm.shoreditch#66]
Agileware are happy to work on this issue. Please let us know if anyone on your team is currently working on it so we do not duplicate our efforts.

1. The individual, organisation and household icon on Find participants page does not pop up a contact summary box.
2. The icon style on Find participants page (left) does not consistent with other pages (right).
![icon-1](https://user-images.githubusercontent.com/32181595/30732137-711c0d78-9fb4-11e7-99fc-7ec1a5a27036.png) ![icon](https://user-images.githubusercontent.com/32181595/30732138-711d93b4-9fb4-11e7-87ff-635251995062.png)

**Comment by agileware-fj** [comment]
This appears fixed.  Please close.

**Comment by mukeshcompucorp** [comment]
@AkA84 This is been fixed with global icons on all places, we can close this.
Ref: https://github.com/civicrm/org.civicrm.shoreditch/pull/95
