### ISSUE TITLE
CIVUP-47 Add Event button, New Mailing button and New SMS button overlap with text

### ISSUE THREAD

**Issue by agileware-ploy** [civicrm/org.civicrm.shoreditch#67]
Agileware are happy to work on this issue. Please let us know if anyone on your team is currently working on it so we do not duplicate our efforts.

Add Event button overlaps with alphabetical filter.

![manage_events](https://user-images.githubusercontent.com/32181595/30732229-e3bac81a-9fb4-11e7-8ba9-032dd88a5b22.png)

New Mailing button and New SMS overlaps with text

![find_mailings](https://user-images.githubusercontent.com/32181595/30732209-cf94e79e-9fb4-11e7-9be9-cba0aae2162d.png)
![find_mass_sms](https://user-images.githubusercontent.com/32181595/30732210-cf98c97c-9fb4-11e7-9609-212573a2d627.png)

**Comment by agileware-fj** [comment]
These appear fixed.  Please close.

**Comment by mukeshcompucorp** [comment]
@AkA84 This is fixed as part of https://github.com/civicrm/org.civicrm.shoreditch/pull/96, we can close this.
