### ISSUE TITLE
CIVUP-48 Huge amount of space between checkbox and its label under Fees and Tell a Friend tab on Configure Event page

### ISSUE THREAD

**Issue by agileware-ploy** [civicrm/org.civicrm.shoreditch#68]
Agileware are happy to work on this issue. Please let us know if anyone on your team is currently working on it so we do not duplicate our efforts.

There is huge amount of space between checkbox and its label under Fees and Tell a Friend tab on Configure Event page.

1. **Fee** -  The checkbox and label for Enable Pay Later option are apart from each other. The alignment of text is not consistent as well.

![configure_event_-_fees](https://user-images.githubusercontent.com/32181595/30732317-5215929a-9fb5-11e7-915c-08b46e3e5ef5.png)

2. **Tell a Friend** - lots of space between checkbox and label

![configure_event_-_tell_a_friend](https://user-images.githubusercontent.com/32181595/30732316-5213017e-9fb5-11e7-80be-da792119a1ae.png)

**Comment by agileware-fj** [comment]
These appear fixed.  Please close.

**Comment by mukeshcompucorp** [comment]
@AkA84 This is fixed as part of global form consolidations in various PRs, this issue no longer reproduces, we can close this
