### ISSUE TITLE
CIVUP-49 Inconsistent text alignment on New Schedule Reminder pop up window

### ISSUE THREAD

**Issue by agileware-ploy** [civicrm/org.civicrm.shoreditch#69]
Agileware are happy to work on this issue. Please let us know if anyone on your team is currently working on it so we do not duplicate our efforts.

Under the Schedule reminders tab on Configuration Event page, when click Add Reminder, the alignment of text is inconsistent on the New Schedule Reminder pop up window. 

![configure_event_-_textalignment](https://user-images.githubusercontent.com/32181595/30732410-c76a6ab6-9fb5-11e7-908f-ebae6a0adb0e.png)

**Comment by agileware-fj** [comment]
Alignment issues seem to be fixed.

The "Record activity"... label is constrained by the markup provided by CiviCRM core, so probably not something that can be fixed here.

Please close.

**Comment by mukeshcompucorp** [comment]
@AkA84 these are fixed as global consolidation in various PRs and issue is no longer reproducible, we can close this
