### ISSUE TITLE
CIVUP-50 Help icon appears behind the blue background on Create new mailing screen

### ISSUE THREAD

**Issue by agileware-ploy** [civicrm/org.civicrm.shoreditch#70]
Agileware are happy to work on this issue. Please let us know if anyone on your team is currently working on it so we do not duplicate our efforts.

Help icon on Create new mailing screen appears behind the blue background 

![mailing](https://user-images.githubusercontent.com/32181595/30732476-1828af08-9fb6-11e7-833c-caf2565e6484.png)

**Comment by agileware-fj** [comment]
Appears fixed.  Please close.

**Comment by mukeshcompucorp** [comment]
@AkA84 No longer reproducible, we can close this
