### ISSUE TITLE
CIVUP-51 When creating New Membership type, the selected radio button not displaying properly

### ISSUE THREAD

**Issue by agileware-ploy** [civicrm/org.civicrm.shoreditch#71]
Agileware are happy to work on this issue. Please let us know if anyone on your team is currently working on it so we do not duplicate our efforts.

When creating New Membership type, the selected radio button of Auto-renew Option not displaying properly. Please see screenshot. 

![radio_button_-_membership_types](https://user-images.githubusercontent.com/32181595/30732525-509d2df0-9fb6-11e7-9bf3-fad0bd5fa07b.png)

**Comment by agileware-fj** [comment]
This appears fixed.  Please close.
