### ISSUE TITLE
CIVUP-52 Left column under Filters tab on Reports page is too narrow, forcing the text to appear in different lines

### ISSUE THREAD

**Issue by agileware-ploy** [civicrm/org.civicrm.shoreditch#72]
Agileware are happy to work on this issue. Please let us know if anyone on your team is currently working on it so we do not duplicate our efforts.

When view the report results, left column under Filters tab is too narrow, forcing the text to appear in different lines. 

![filters_column](https://user-images.githubusercontent.com/32181595/30732580-9d258096-9fb6-11e7-91e1-6f9d28761a2a.png)

**Comment by agileware-fj** [comment]
This appears fixed. Please close.

**Comment by mukeshcompucorp** [comment]
@AkA84 fix as part of global table consolidations, no longer reproducible
