### ISSUE TITLE
CIVUP-53 Cancel button on New Credit Card Contribution page is not aligned properly

### ISSUE THREAD

**Issue by agileware-ploy** [civicrm/org.civicrm.shoreditch#73]
Agileware are happy to work on this issue. Please let us know if anyone on your team is currently working on it so we do not duplicate our efforts.

When navigate to New Contribution and click Submit Credit Card Contribution button, New Credit Card Contribution screen will be displayed. On this page, the cancel button is not aligned properly.

![new_credit_card_contribution___canberra_all_stars](https://user-images.githubusercontent.com/32181595/30732660-ef252e28-9fb6-11e7-8ce3-de7c703d3452.png)

**Comment by agileware-fj** [comment]
This appears fixed. Please close

**Comment by mukeshcompucorp** [comment]
@AkA84 This is fixed as part of global form  and button consolidations, it no longer producible. we can close this
