### ISSUE TITLE
Manage Contribution Page is missing words

### ISSUE THREAD

**Issue by KarinG** [civicrm/org.civicrm.shoreditch#75]
Top: w/ adminimal_theme
Bottom: w/ shoreditch

Missing: Configure; Contributions; Links and more

![image](https://user-images.githubusercontent.com/5340555/30985478-3ee6d816-a45e-11e7-9230-3854a7ca9057.png)

**Comment by mukeshcompucorp** [comment]
@AkA84 This is fixed as part of https://github.com/civicrm/org.civicrm.shoreditch/pull/177 we can close it.
