### ISSUE TITLE
Scrollbars appear on every table cell of list of Extensions

### ISSUE THREAD

**Issue by herbdool** [civicrm/org.civicrm.shoreditch#76]
On the Extensions page:

![selection_007](https://user-images.githubusercontent.com/1071483/31057721-7e2250f6-a6b5-11e7-9c31-71de3bc4bab8.png)

The scrollbars take up a lot of space and are useless.

**Comment by mattwire** [comment]
@AkA84 Removing `overflow: scroll;` from `scss/civicrm/administer/settings/_extensions.scss` seems to fix this

**Comment by mukeshcompucorp** [comment]
@AkA84 this is fixed as part of  https://github.com/civicrm/org.civicrm.shoreditch/pull/126, we can close this
