### ISSUE TITLE
Old style checkboxes don't show up on slower computers

### ISSUE THREAD

**Issue by eruraindil** [civicrm/org.civicrm.shoreditch#77]
Observed in latest versions of Chrome & FF on Windows.

It is especially noticeable in the merge contact screen. Also happens on the search results, but triggering a DOM update causes the checkboxes to appear, which makes me think it's related to the mutation observer in js/radio-checkbox.js.

On slower computers the checkboxes don't appear.
![image](https://user-images.githubusercontent.com/2336581/31101040-3abda6e2-a789-11e7-8e76-6486d63e3560.png)

Expected result, (which seems to work on faster hardware): the checkboxes appear slightly after the page has loaded.
![image](https://user-images.githubusercontent.com/2336581/31101154-a92b6a6a-a789-11e7-84c5-2ee7505e48c0.png)

**Comment by mukeshcompucorp** [comment]
@AkA84 as a part of https://github.com/civicrm/org.civicrm.shoreditch/pull/123, we do not have styled checkboxes anymore and js to hide it initially, and hence, this issue is now not produced.

You can close this
