### ISSUE TITLE
my civicrm navigation menu disappeared upon install

### ISSUE THREAD

**Issue by democratizeit** [civicrm/org.civicrm.shoreditch#82]
Hi.  So I installed the theme extension, and I can see that my theme has changed, but now I have no navigation menu.   where did it go?

**Comment by AkA84** [comment]
@democratizeit can you provide us more info (drupal version, civicrm version, drupal theme used, etc) and a screenshot? Thanks!

**Comment by themak1985** [comment]
Same issue here - 4.7.24, wordpress 4.8.2 and latest shoreditch alpha 11.  switching back to default theme fixes issue.  Returning to Shoreditch - CiviCRM menu disappears. Note, Alpha 10 did not have this issue.

**Comment by brouwser** [comment]
Same here. Reset paths (Settings menu) solved it for me.

**Comment by brouwser** [comment]
Sorry, no it didn't... 4.7.25, Drupal 7.56, shoreditch alph12.

**Comment by mattwire** [comment]
See PR #90 - I think that will fix it for you.

**Comment by themak1985** [comment]
@mattwire this is still an issue, even with Alpha14.
Using latest wordpress and civicrm.

**Comment by reswild** [comment]
@themak1985 This is still an issue with Alpha 14 because this fix hasn't been committed yet, but you can always manually edit the custom-civicrm.css file and remove the z-index rule from #civicrm-menu.

**Comment by AkA84** [comment]
@democratizeit this should have been fixed by #270 , please check the PR for additional information

**Comment by mattwire** [comment]
Thanks, tested in Drupal/Wordpress and it does seem to be fixed :-) Raised civicrm/civicrm-core#12632 for Joomla menu issue.
